name: TypeScript Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run lint --if-present
    - run: npm run build --if-present
    - run: npm test --if-present
